### ISSUE TITLE
"Configure github" button has no action.

### ISSUE THREAD

**Issue by jayunit100** [waartaa/waartaa#159]
There is a "configure github" button at the top of the welcome screen, but I don't see any way to use it - is this a server side action, or the client should be able to do it?

**Comment by rtnpro** [comment]
"Configure github" involves some server side actions too. It's not working currently because of some bugs in the https://github.com/mangasocial/meteor-accounts-ui-bootstrap-3 plugin. We need to revamp the login/signup flow with more auth processes: FAS, Facebook, Google apart from Github and also make it more streamlined and bug free. We may need to write our own code for this.

However, currently, I am tied with revamping the chat interface. So, this will take some time if I have to do this. If you are interested to work on it, let me know.

**Comment by sheeshmohsin** [comment]
I am interested to work on it, please guide me.

**Comment by rtnpro** [comment]
@sheeshmohsin , we need to revamp our accounts pages completely. It's gonna be a big task and a major feature. Up for it?

**Comment by sheeshmohsin** [comment]
yes, sure, just guide me, and i will do that :)
